export const PRESENCE_ENDPOINT = 'https://presence.roblox.com/v1/presence/register-app-presence';
export const API_ENDPOINT = 'https://api.roblox.com';
export const LOCATION_HOME = {location: 'Home'};
export const REALTIME_ENDPOINT = 'realtime.roblox.com/notifications';
export const HTTPS_PROTOCOL = 'https://';
export const WSS_PROTOCOL = 'wss://';
export const connectionData = JSON.stringify([{'name': 'usernotificationhub'}]);
export const USER_AGENT = 'roblox.ts';
export const ROBLOX_URL = 'https://www.roblox.com';
export const START = '/start?transport=webSockets&clientProtocol=1.5';
